# YAML configuration for a Kubernetes Secret named "mongodb-secret" in the namespace "karsajobs-ns" containing a MongoDB root username and password.
apiVersion: v1  # Defines the API version of the Kubernetes object.
kind: Secret  # Indicates that the YAML defines a Kubernetes Secret.
metadata:  # Metadata for the Kubernetes Secret.
  name: mongodb-secret  # Specifies the name of the Secret as "mongodb-secret".
  namespace: karsajobs-ns  # Specifies the namespace for the Secret as "karsajobs-ns".
type: Opaque  # Indicates the type of the Secret as "Opaque".
stringData:  # Contains the string data for the Secret.
  MONGO_ROOT_USERNAME: admin  # Specifies the MongoDB root username as "admin".
data:  # Contains the encoded data for the Secret.
  MONGO_ROOT_PASSWORD: c3VwZXJzZWNyZXRwYXNzd29yZA==  # Specifies the MongoDB root password as a base64 encoded string 'supersecretpassword'